swagger: '2.0'
info:
  version: '1.0.0'
  title: Federal Business Opportunity API
  description: 
    This API is used to track and compile federal business opportunities scraped from the following website.  http://www.fbodaily.com/
  
paths:
  /op/{id}:
    parameters:
      - in: path
        name: id
        type: string
        required: true
    get:
      summary: Get an opportunity by id
      produces:
        - application/xml
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Opportunity"
        400:
          description: Invalid id
        404:
          description: Resource not found
          
definitions:
  Opportunity:
    type: object
    properties:
      icf_biz_opp_id:
        type: integer
        format: int64