AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Federal Business Opportunity API'

Mappings:

  Constants:
    ValueOf:
      NodeVersion: 'nodejs6.10'

Resources:

  ApiGateway:
    Type: 'AWS::Serverless::Api'
    StageName: 'dev'
    DefinitionUri: 'swagger.yaml'

  # ~~~ Lambda Functions ~~~

  ApexGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: !FindInMap [ Constants,  ValueOf, NodeVersion ]
      Handler: 'functions/version.handler'
      Events:
        Http:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ApiGateway

  LocalTablePost:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: !FindInMap [ Constants,  ValueOf, NodeVersion ]
      Handler: 'functions/local-table.handler'
      Events:
        Http:
          Type: Api
          Properties:
            Path: /local-table
            Method: POST
            RestApiId: !Ref ApiGateway

  OpportunityGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: !FindInMap [ Constants,  ValueOf, NodeVersion ]
      Handler: 'functions/opportunity.handler'
      Events:
        Http:
          Type: Api
          Properties:
            Path: /opportunity/{id}
            Method: GET
            RestApiId: !Ref ApiGateway

  OpportunityPost:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: !FindInMap [ Constants,  ValueOf, NodeVersion ]
      Handler: 'functions/opportunity.handler'
      Events:
        Http:
          Type: Api
          Properties:
            Path: /opportunity
            Method: POST
            RestApiId: !Ref ApiGateway

  VersionGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: !FindInMap [ Constants,  ValueOf, NodeVersion ]
      Handler: 'functions/version.handler'
      Events:
        Http:
          Type: Api
          Properties:
            Path: /version
            Method: GET
            RestApiId: !Ref ApiGateway

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/dev'